export const ACTION_TYPES = {
    //Users
    GET_UNAPPROVED_USERS: "GET_UNAPPROVED_USERS",
    GET_DEACTIVATE_USERS: "GET_DEACTIVATE_USERS",
    UPDATE_USER_STATUS: "UPDATE_USER_STATUS",
    GET_SINGLE_USER: "GET_SINGLE_USER",

  
    //UNIVERSITY-FINDER
    ADD_UNIVERSITY_FINDER: "ADD_UNIVERSITY_FINDER",
    GET_UNIVERSITY_FINDERS: "GET_UNIVERSITY_FINDERS",
    UPDATE_UNIVERSITY_FINDER: "UPDATE_UNIVERSITY_FINDER",
    DELETE_UNIVERSITY_FINDERS: "DELETE_UNIVERSITY_FINDERS",
    
    //SCHOLARSHIPS
    ADD_SCHOLARSHIP: "ADD_SCHOLARSHIP",
    GET_SCHOLARSHIPS: "GET_SCHOLARSHIPS",
    UPDATE_SCHOLARSHIP: "UPDATE_SCHOLARSHIP",
    DELETE_SCHOLARSHIP: "DELETE_SCHOLARSHIP",
  
    //ACCOMODATIONS
    ADD_ACCOMODATION: "ADD_ACCOMODATION",
    GET_ACCOMODATIONS: "GET_ACCOMODATIONS",
    UPDATE_ACCOMODATION: "UPDATE_ACCOMODATION",
    DELETE_ACCOMODATION: "DELETE_ACCOMODATION",
  
    //Customers Messages
    GET_CUSTOMERS_MESSAGES: "GET_CUSTOMERS_MESSAGES",
    DELETE_CUSTOMERS_MESSAGES: "DELETE_CUSTOMERS_MESSAGES",
    SUBMIT_RESPONSE_ON_CUSTOMERS_MESSAGES: "SUBMIT_RESPONSE_ON_CUSTOMERS_MESSAGES",
  
    //Form-submission
    ADD_NEW_FORM_SUBMISSION: "ADD_NEW_FORM_SUBMISSION",
  
    
    //Blogs
    GET_BLOGS: "GET_BLOGS",
    GET_SINGLE_BLOG: "GET_SINGLE_BLOG",

    //progress
    PROGRESS_BAR_STATE: "PROGRESS_BAR_STATE",
  
    //login
    LOGIN: "LOGIN",
  };
  