export const ACTION_TYPES = {
  //Users
  SET_ADMIN: 'SET_ADMIN',
  GET_DEACTIVATE_USERS: 'GET_DEACTIVATE_USERS',
  GET_ADMIN_CREATED_USERS: 'GET_ADMIN_CREATED_USERS',
  GET_WEBSITE_CONTACTED_USERS: 'GET_WEBSITE_CONTACTED_USERS',
  GET_WEBSITE_UNCONTACTED_USERS: 'GET_WEBSITE_UNCONTACTED_USERS',
  UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
  UPDATE_TO_CONTACTED_STATUS: 'UPDATE_TO_CONTACTED_STATUS',
  GET_SINGLE_USER: 'GET_SINGLE_USER',
  GET_SINGLE_USER_BY_ID: 'GET_SINGLE_USER_BY_ID',

  //Customers Messages
  GET_CUSTOMERS_MESSAGES: 'GET_CUSTOMERS_MESSAGES',
  DELETE_CUSTOMERS_MESSAGES: 'DELETE_CUSTOMERS_MESSAGES',
  SUBMIT_RESPONSE_ON_CUSTOMERS_MESSAGES:
    'SUBMIT_RESPONSE_ON_CUSTOMERS_MESSAGES',

  //UNIVERSITY-FINDER
  ADD_UNIVERSITY_FINDER: 'ADD_UNIVERSITY_FINDER',
  GET_UNIVERSITY_FINDERS: 'GET_UNIVERSITY_FINDERS',
  GET_ALL_SINGLE_USER_UNIVERSITY_FINDERS:
    'GET_ALL_SINGLE_USER_UNIVERSITY_FINDERS',
  GET_ALL_SINGLE_USER_UNIVERSITY_FINDERS_BY_ID:
    'GET_ALL_SINGLE_USER_UNIVERSITY_FINDERS_BY_ID',
  GET_UNIVERSITY_FINDER: 'GET_UNIVERSITY_FINDER',
  UPDATE_UNIVERSITY_FINDER: 'UPDATE_UNIVERSITY_FINDER',
  DELETE_UNIVERSITY_FINDERS: 'DELETE_UNIVERSITY_FINDERS',

  //SCHOLARSHIPS
  ADD_SCHOLARSHIP: 'ADD_SCHOLARSHIP',
  GET_SCHOLARSHIPS: 'GET_SCHOLARSHIPS',
  GET_ALL_SINGLE_USER_SCHOLARSHIPS: 'GET_ALL_SINGLE_USER_SCHOLARSHIPS',
  GET_ALL_SINGLE_USER_SCHOLARSHIPS_BY_ID:
    'GET_ALL_SINGLE_USER_SCHOLARSHIPS_BY_ID',
  GET_SCHOLARSHIP: 'GET_SCHOLARSHIP',
  UPDATE_SCHOLARSHIP: 'UPDATE_SCHOLARSHIP',
  DELETE_SCHOLARSHIP: 'DELETE_SCHOLARSHIP',

  //ACCOMODATIONS
  ADD_ACCOMODATION: 'ADD_ACCOMODATION',
  GET_ACCOMODATIONS: 'GET_ACCOMODATIONS',
  GET_ALL_SINGLE_USER_ACCOMODATIONS: 'GET_ALL_SINGLE_USER_ACCOMODATIONS',
  GET_ALL_SINGLE_USER_ACCOMODATIONS_BY_ID:
    'GET_ALL_SINGLE_USER_ACCOMODATIONS_BY_ID',
  GET_ACCOMODATION: 'GET_ACCOMODATION',
  UPDATE_ACCOMODATION: 'UPDATE_ACCOMODATION',
  DELETE_ACCOMODATION: 'DELETE_ACCOMODATION',

  //Form-submission
  UPDATE_FORM_SUBMISSION: 'UPDATE_FORM_SUBMISSION',
  GET_ALL_UNCONTACTED_FORM_SUBMISSION: 'GET_ALL_UNCONTACTED_FORM_SUBMISSION',
  GET_ALL_CONTACTED_FORM_SUBMISSION: 'GET_ALL_CONTACTED_FORM_SUBMISSION',

  //Blogs
  SET_BLOG: 'SET_BLOG',
  GET_BLOGS: 'GET_BLOGS',
  GET_ALL_ADMIN_BLOGS: 'GET_ALL_ADMIN_BLOGS',
  GET_SINGLE_BLOG: 'GET_SINGLE_BLOG',
  DELETE_BLOG: 'DELETE_BLOG',
  UPDATE_BLOG: 'UPDATE_BLOG',

  //Dashboard Data
  GET_DASHBOARD_DATA: 'GET_DASHBOARD_DATA',

  //progress
  PROGRESS_BAR_STATE: 'PROGRESS_BAR_STATE',

  //login
  LOGIN: 'LOGIN',
};
